sudo: required
language: minimal
branches:
    only:
        - master
services:
    - docker
jobs:
    include:
        - stage: test # No tests at the moment, so ensure it at least runs
          name: test
          script:
              - docker-compose build
              - docker-compose run server -v --db mysql+pymysql://test:test@db/foobar --dry-run -p 42834
          after_script: docker-compose down
        - stage: deploy
          name: deploy
          script: travis_wait ./container/push.sh
stages:
    - test
    - deploy
